global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'cyw_blackbox'
    static_configs:
      - targets: ['localhost:5002']
    metrics_path: '/metrics'
    scrape_interval: 5s
    honor_labels: true

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 30s
